language: vi

pipeline:
- name: WhitespaceTokenizer
  intent_tokenization_flag: True
  intent_split_symbol: "+"
  token_pattern: None  # Hỗ trợ tốt hơn cho tiếng Việt
  augmentation: 0  # Giảm dữ liệu giả lập để tránh noise

- name: RegexFeaturizer

- name: LexicalSyntacticFeaturizer

- name: CountVectorsFeaturizer
  analyzer: word  # Chỉ dùng word-level để tránh overfitting
  min_ngram: 1
  max_ngram: 2  # Giảm từ 4 xuống 2 để tránh overfitting

- name: DIETClassifier
  epochs: 150  # Tăng epochs để train lâu hơn
  constrain_similarities: true

- name: EntitySynonymMapper

- name: ResponseSelector
  epochs: 150  # Tăng epochs để tăng khả năng hiểu
  constrain_similarities: true

- name: FallbackClassifier
  threshold: 0.45  # Giảm một chút để phản hồi linh hoạt hơn
  core_threshold: 0.45

policies:
- name: MemoizationPolicy
  max_history: 8  # Tăng để mô hình nhớ tốt hơn

- name: RulePolicy

- name: UnexpecTEDIntentPolicy
  max_history: 8  # Tăng để hiểu được nhiều ngữ cảnh hơn
  epochs: 150  # Tăng epochs để train lâu hơn

- name: TEDPolicy
  max_history: 8  # Nhớ dài hơn
  epochs: 150  # Tăng epochs để giảm `loss`
  constrain_similarities: true

assistant_id: 20250318-234357-dry-score
